spring:
  cloud:
    function:
      definition: producer
    stream:
      poller:
        fixed-delay: 5000
      bindings:
        producer-out-0:
          destination: bcaf/notif/input
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://192.168.56.31:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
server:
  port: 8091