spring:
  cloud:
    function:
      definition: consumer
    stream:
      bindings:
        consumer-in-0:
          destination: bcaf/notif/output
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://192.168.56.31:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
server:
  port: 8093